using NovaWallet.Api.Core.Enums;
using UUIDNext;

namespace NovaWallet.Api.Core.Models
{
    /// <summary>
    /// Read/query-friendly record of a completed inter-wallet transfer, written in the
    /// same DB transaction as its <see cref="JournalEntry"/>/<see cref="AccountEntry"/>
    /// pair (see TransferService.ProcessTransferAsync). AccountEntries answers "what
    /// moved, in double-entry terms" and is keyed by AccountId; this table answers "what
    /// transfers happened between which wallets" and is keyed by WalletId directly on
    /// both sides — Narration and the wallet-to-wallet shape of a transfer are
    /// product-domain concepts that don't belong on the ledger's
    /// JournalEntries/AccountEntries tables, yet are exactly what a "list my transfers" /
    /// wallet statement view needs without joining out to Accounts.
    ///
    /// TransactionDate is deliberately passed in by the caller (as the owning
    /// JournalEntry's CreatedAt) rather than stamped independently with DateTime.UtcNow,
    /// so a replayed request's response and this row always agree on the transfer's
    /// timestamp to the tick.
    ///
    /// PaymentReference is its own independently system-generated UUID v7 (via
    /// Uuid.NewSequential()) - deliberately decoupled from JournalEntryId, matching the
    /// project-wide convention that every DB-internal identifier is generated by its own
    /// entity rather than borrowed from another one.
    /// </summary>
    public class WalletTransfer
    {
        public Guid Id { get; }

        /// <summary>The ledger posting for a <see cref="TransferStatus.Completed"/> transfer.
        /// Null for a <see cref="TransferStatus.Failed"/> transfer, which never posts.</summary>
        public Guid? JournalEntryId { get; }
        public JournalEntry? JournalEntry { get; private set; }
        public Guid SourceWalletId { get; }
        public Wallet? SourceWallet { get; private set; }
        public Guid DestinationWalletId { get; }
        public Wallet? DestinationWallet { get; private set; }
        public long AmountKobo { get; }
        public string? Narration { get; }
        public string PaymentReference { get; }
        public TransferStatus Status { get; private set; }

        /// <summary>Client-supplied Idempotency-Key. Unique: one row per key, whether the
        /// transfer completed or failed.</summary>
        public string IdempotencyKey { get; }

        /// <summary>SHA-256 of the canonical request payload, used to reject the same key
        /// reused with a different payload.</summary>
        public string RequestPayloadHash { get; }

        /// <summary>NIP response code of a failed transfer (e.g. "51"). Null when not failed.</summary>
        public string? FailureCode { get; }

        /// <summary>Human-readable reason of a failed transfer. Null when not failed.</summary>
        public string? FailureReason { get; }
        public DateTime TransactionDate { get; }
        public DateTime DateModified { get; private set; }

        private WalletTransfer(Guid id, Guid? journalEntryId, Guid sourceWalletId, Guid destinationWalletId,
            long amountKobo, string? narration, string paymentReference, TransferStatus status,
            string idempotencyKey, string requestPayloadHash, string? failureCode, string? failureReason,
            DateTime transactionDate, DateTime dateModified)
        {
            Id = id;
            JournalEntryId = journalEntryId;
            SourceWalletId = sourceWalletId;
            DestinationWalletId = destinationWalletId;
            AmountKobo = amountKobo;
            Narration = narration;
            PaymentReference = paymentReference;
            Status = status;
            IdempotencyKey = idempotencyKey;
            RequestPayloadHash = requestPayloadHash;
            FailureCode = failureCode;
            FailureReason = failureReason;
            TransactionDate = TruncateToMicroseconds(transactionDate);
            DateModified = TruncateToMicroseconds(dateModified);
        }

        /// <summary>
        /// Postgres stores timestamps at microsecond precision while <see cref="DateTime.UtcNow"/>
        /// has 100 ns ticks. Truncating up front makes the value the caller is first shown identical
        /// to the one read back from the table on a replay or requery - otherwise the two responses
        /// differ in the last fractional digit and an "identical replay" is not byte-identical.
        /// </summary>
        private static DateTime TruncateToMicroseconds(DateTime value) =>
            new(value.Ticks - (value.Ticks % 10), value.Kind);

        public static WalletTransfer Create(Guid journalEntryId, Guid sourceWalletId, Guid destinationWalletId,
            long amountKobo, string? narration, string idempotencyKey, string requestPayloadHash,
            DateTime transactionDate)
        {
            if (journalEntryId == Guid.Empty)
                throw new ArgumentException("JournalEntryId is required.", nameof(journalEntryId));

            ValidateCommon(sourceWalletId, destinationWalletId, amountKobo, idempotencyKey, requestPayloadHash);

            return new WalletTransfer(
                id: Uuid.NewSequential(),
                journalEntryId: journalEntryId,
                sourceWalletId: sourceWalletId,
                destinationWalletId: destinationWalletId,
                amountKobo: amountKobo,
                narration: narration,
                paymentReference: Uuid.NewSequential().ToString(),
                status: TransferStatus.Completed,
                idempotencyKey: idempotencyKey,
                requestPayloadHash: requestPayloadHash,
                failureCode: null,
                failureReason: null,
                transactionDate: transactionDate,
                dateModified: transactionDate);
        }

        /// <summary>
        /// Records a transfer that was rejected after both wallets were confirmed to exist.
        /// There is no ledger posting, so <see cref="JournalEntryId"/> stays null.
        /// </summary>
        public static WalletTransfer CreateFailed(Guid sourceWalletId, Guid destinationWalletId,
            long amountKobo, string? narration, string idempotencyKey, string requestPayloadHash,
            string failureCode, string failureReason)
        {
            ValidateCommon(sourceWalletId, destinationWalletId, amountKobo, idempotencyKey, requestPayloadHash);

            if (string.IsNullOrWhiteSpace(failureCode))
                throw new ArgumentException("FailureCode is required.", nameof(failureCode));

            var now = DateTime.UtcNow;

            return new WalletTransfer(
                id: Uuid.NewSequential(),
                journalEntryId: null,
                sourceWalletId: sourceWalletId,
                destinationWalletId: destinationWalletId,
                amountKobo: amountKobo,
                narration: narration,
                paymentReference: Uuid.NewSequential().ToString(),
                status: TransferStatus.Failed,
                idempotencyKey: idempotencyKey,
                requestPayloadHash: requestPayloadHash,
                failureCode: failureCode,
                failureReason: string.IsNullOrWhiteSpace(failureReason)
                    ? null
                    : (failureReason.Length > 500 ? failureReason[..500] : failureReason),
                transactionDate: now,
                dateModified: now);
        }

        private static void ValidateCommon(Guid sourceWalletId, Guid destinationWalletId, long amountKobo,
            string idempotencyKey, string requestPayloadHash)
        {
            if (sourceWalletId == Guid.Empty)
                throw new ArgumentException("SourceWalletId is required.", nameof(sourceWalletId));
            if (destinationWalletId == Guid.Empty)
                throw new ArgumentException("DestinationWalletId is required.", nameof(destinationWalletId));
            if (sourceWalletId == destinationWalletId)
                throw new ArgumentException("SourceWalletId and DestinationWalletId must differ.", nameof(destinationWalletId));
            if (amountKobo <= 0)
                throw new ArgumentOutOfRangeException(nameof(amountKobo), "AmountKobo must be positive.");
            if (string.IsNullOrWhiteSpace(idempotencyKey))
                throw new ArgumentException("IdempotencyKey is required.", nameof(idempotencyKey));
            if (string.IsNullOrWhiteSpace(requestPayloadHash))
                throw new ArgumentException("RequestPayloadHash is required.", nameof(requestPayloadHash));
        }

        /// <summary>Schema completeness for a future reversal feature - not wired to any
        /// endpoint today.</summary>
        public void MarkReversed()
        {
            if (Status != TransferStatus.Completed)
                throw new InvalidOperationException($"WalletTransfer {Id} is not Completed (status: {Status}).");

            Status = TransferStatus.Reversed;
            DateModified = DateTime.UtcNow;
        }
    }
}
