// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovaWallet.Api.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NovaWallet.Api.Migrations
{
    [DbContext(typeof(NovaWalletDbContext))]
    partial class NovaWalletDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NovaWallet.Api.Core.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("AccountType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("NGN");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("NovaWallet.Api.Core.Models.AccountEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreditAmountKobo")
                        .HasColumnType("bigint");

                    b.Property<long>("DebitAmountKobo")
                        .HasColumnType("bigint");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JournalEntryId");

                    b.HasIndex("AccountId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_AccountEntries_AccountId_CreatedAt");

                    b.ToTable("AccountEntries", null, t =>
                        {
                            t.HasCheckConstraint("CHK_AccountEntries_ExclusiveSign", "(\"DebitAmountKobo\" > 0 AND \"CreditAmountKobo\" = 0)\r\nOR\r\n(\"DebitAmountKobo\" = 0 AND \"CreditAmountKobo\" > 0)");
                        });
                });

            modelBuilder.Entity("NovaWallet.Api.Core.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ActorSubject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("BalanceAfterKobo")
                        .HasColumnType("bigint");

                    b.Property<long>("BalanceBeforeKobo")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("NovaWallet.Api.Core.Models.DepositOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExternalCreditRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id");

                    b.HasIndex("ExternalCreditRequestId");

                    b.ToTable("DepositOutbox", (string)null);
                });

            modelBuilder.Entity("NovaWallet.Api.Core.Models.ExternalCreditRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AmountKobo")
                        .HasColumnType("bigint");

                    b.Property<string>("BeneficiaryAccountNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginatingAccountNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("OriginatingBankCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("TransactionReference")
                        .IsUnique();

                    b.ToTable("ExternalCreditRequests", null, t =>
                        {
                            t.HasCheckConstraint("CHK_ExternalCreditRequest_AmountKobo_Positive", "\"AmountKobo\" > 0");
                        });
                });

            modelBuilder.Entity("NovaWallet.Api.Core.Models.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RequestPayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("JournalEntries", (string)null);
                });

            modelBuilder.Entity("NovaWallet.Api.Core.Models.TransferOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("TransferCompleted");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id");

                    b.HasIndex("JournalEntryId");

                    b.ToTable("TransferOutbox", (string)null);
                });

            modelBuilder.Entity("NovaWallet.Api.Core.Models.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<long>("AvailableBalanceKobo")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("NGN");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Wallets", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Wallet_AvailableBalanceKobo_NonNegative", "\"AvailableBalanceKobo\" >= 0");
                        });
                });

            modelBuilder.Entity("NovaWallet.Api.Core.Models.WalletDailyUsage", b =>
                {
                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("UsageDate")
                        .HasColumnType("date");

                    b.Property<long>("TotalSpentKobo")
                        .HasColumnType("bigint");

                    b.HasKey("WalletId", "UsageDate");

                    b.ToTable("WalletDailyUsage", (string)null);
                });

            modelBuilder.Entity("NovaWallet.Api.Core.Models.AccountEntry", b =>
                {
                    b.HasOne("NovaWallet.Api.Core.Models.Account", "Account")
                        .WithMany("Entries")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NovaWallet.Api.Core.Models.JournalEntry", "JournalEntry")
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("NovaWallet.Api.Core.Models.AuditLog", b =>
                {
                    b.HasOne("NovaWallet.Api.Core.Models.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("NovaWallet.Api.Core.Models.DepositOutbox", b =>
                {
                    b.HasOne("NovaWallet.Api.Core.Models.ExternalCreditRequest", "ExternalCreditRequest")
                        .WithMany("OutboxEntries")
                        .HasForeignKey("ExternalCreditRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExternalCreditRequest");
                });

            modelBuilder.Entity("NovaWallet.Api.Core.Models.TransferOutbox", b =>
                {
                    b.HasOne("NovaWallet.Api.Core.Models.JournalEntry", "JournalEntry")
                        .WithMany()
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("NovaWallet.Api.Core.Models.Wallet", b =>
                {
                    b.HasOne("NovaWallet.Api.Core.Models.Account", "Account")
                        .WithOne()
                        .HasForeignKey("NovaWallet.Api.Core.Models.Wallet", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("NovaWallet.Api.Core.Models.WalletDailyUsage", b =>
                {
                    b.HasOne("NovaWallet.Api.Core.Models.Wallet", "Wallet")
                        .WithMany("DailyUsages")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("NovaWallet.Api.Core.Models.Account", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("NovaWallet.Api.Core.Models.ExternalCreditRequest", b =>
                {
                    b.Navigation("OutboxEntries");
                });

            modelBuilder.Entity("NovaWallet.Api.Core.Models.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("NovaWallet.Api.Core.Models.Wallet", b =>
                {
                    b.Navigation("DailyUsages");
                });
#pragma warning restore 612, 618
        }
    }
}
